DEBUG:root:got to submitProjectEval!!
DEBUG:root:get a post request
DEBUG:root:translated the form
DEBUG:root:form errors:
INFO:django.utils.autoreload:/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/models.py changed, reloading.
DEBUG:root:got to submitProjectEval!!
DEBUG:root:get a post request
DEBUG:root:translated the form
DEBUG:root:form errors:
INFO:django.utils.autoreload:/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py changed, reloading.
DEBUG:root:got to submitProjectEval!!
DEBUG:root:form is valid
ERROR:django.request:Internal Server Error: /project_eval_form/submitted
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py", line 13, in submittedProjectEvalView
    return submitProjectEval(request)
  File "//anaconda3/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py", line 63, in submitProjectEval
    score.save()
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1429, in execute_sql
    cursor = super().execute_sql(result_type)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1087, in execute_sql
    sql, params = self.as_sql()
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1395, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 793, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 788, in get_db_prep_value
    value = self.get_prep_value(value)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1024, in get_prep_value
    return self.to_python(value)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1017, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ["'true' value must be either True or False."]
INFO:django.utils.autoreload:/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py changed, reloading.
DEBUG:root:got to submitProjectEval!!
DEBUG:root:form is valid
ERROR:django.request:Internal Server Error: /project_eval_form/submitted
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py", line 13, in submittedProjectEvalView
    return submitProjectEval(request)
  File "//anaconda3/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py", line 47, in submitProjectEval
    manu_consideration = makeBool(request.POST.get("manu_consideration"))
  File "/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py", line 17, in makeBool
    return true
NameError: name 'true' is not defined
INFO:django.utils.autoreload:/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py changed, reloading.
DEBUG:root:got to submitProjectEval!!
DEBUG:root:form is valid
ERROR:django.request:Internal Server Error: /project_eval_form/submitted
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InsufficientPrivilege: permission denied for relation scoringsystem_projecteval


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py", line 13, in submittedProjectEvalView
    return submitProjectEval(request)
  File "//anaconda3/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py", line 68, in submitProjectEval
    score.save()
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1429, in execute_sql
    cursor = super().execute_sql(result_type)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: permission denied for relation scoringsystem_projecteval

DEBUG:root:got to submitProjectEval!!
DEBUG:root:form is valid
ERROR:django.request:Internal Server Error: /project_eval_form/submitted
Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InsufficientPrivilege: permission denied for relation scoringsystem_projecteval


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "//anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py", line 13, in submittedProjectEvalView
    return submitProjectEval(request)
  File "//anaconda3/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py", line 68, in submitProjectEval
    score.save()
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 851, in _save_table
    forced_update)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/base.py", line 900, in _do_update
    return filtered._update(values) > 0
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1429, in execute_sql
    cursor = super().execute_sql(result_type)
  File "//anaconda3/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "//anaconda3/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "//anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: permission denied for relation scoringsystem_projecteval

DEBUG:root:got to submitProjectEval!!
DEBUG:root:form is valid
WARNING:django.request:Not Found: /css/bootstrap.css
WARNING:django.request:Not Found: /js/jquery-3.4.1.js
WARNING:django.request:Not Found: /js/bootstrap.js
WARNING:django.request:Not Found: /js/functions.js
WARNING:django.request:Not Found: /project_eval_form/events.js
WARNING:django.request:Not Found: /css/bootstrap.css
WARNING:django.request:Not Found: /js/jquery-3.4.1.js
WARNING:django.request:Not Found: /js/bootstrap.js
DEBUG:root:got to submitProjectEval!!
DEBUG:root:form is valid
INFO:django.utils.autoreload:/Users/sevictor/Documents/GitHub/Senior-Design-Scoring-System/Django/scoringsystem/scoringsystem/views.py changed, reloading.
